auth, chat and user initials
ali-iqbal-brainx/Real-time-chat-web-app-back-end pull request #1
Opened 2023-03-01 09:53 UTC by ali-iqbal-brainx

1. auth 
2. user
3. chat

2023-03-03 07:03 UTC, ali-faiz-brainx requested changes

2023-03-03 07:03 UTC, ali-faiz-brainx commented on controllers/chatController.js
> +        const chatCode = Math.floor(100000 + Math.random() * 900000).toString();
use constant values instead of hardcoded

2023-03-03 07:03 UTC, ali-faiz-brainx commented on index.js
> +    origin:'http://localhost:3000', //or whatever port your frontend is using
Pust constents in envs instead of hard coded

2023-04-20 17:27 UTC, usama-masood-brainx requested changes

2023-04-20 17:27 UTC, usama-masood-brainx commented on controllers/authController.js
> +        const { name, password } = request.body;
check if user already exist

2023-04-20 17:27 UTC, usama-masood-brainx commented on index.js
> +    origin: 'http://localhost:3000', //or whatever port your frontend is using
put dynamic constants in env file

2023-04-20 17:27 UTC, usama-masood-brainx commented on index.js
> +        origin: 'http://localhost:3000',
put dynamic constants in env file

2023-04-20 17:27 UTC, usama-masood-brainx commented on middlewares/userMiddleware.js
> +        if (password.length<8) {
use password regex for the pattern (1 uppercase, 1 symbol, 1 number, and min 8 char)

2023-04-20 17:27 UTC, usama-masood-brainx commented on models/one_to_one.js
> +            seenBy: [],
define type of object in seenBy array

2023-04-20 17:27 UTC, usama-masood-brainx commented on services/jwtService.js
> +require('dotenv').config();
require dotenv at start of server script instead of individual modules

2023-04-26 08:47 UTC, merged